source ~/.bashrc

# Bash completion scripts
source /usr/local/etc/bash_completion.d/brew
source /usr/local/etc/bash_completion.d/eb_completion.bash
source /usr/local/etc/bash_completion.d/hub.bash_completion.sh
source /usr/local/etc/bash_completion.d/git-completion.bash
# source /usr/local/etc/bash_completion.d/npm

# export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# Older version of Elasticsearch and Node
export PATH="/usr/local/opt/elasticsearch@5.6/bin:$PATH"
export PATH="/usr/local/opt/node@8/bin:$PATH"
# Older version of PHP and MySQL
export PATH="/usr/local/opt/php@7.1/bin:$PATH"
export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
# Add Yarn to path
export PATH="$PATH:`yarn global bin`"
export GPG_TTY=$(tty)

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Load rbenv
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# https://openradar.appspot.com/27348363
# This is a fix for macOS Sierra
# -A flag adds all identities stored in keychain
ssh-add -A &> /dev/null
